###############################################################################
# 0xTheProDev/gitlab-mirror : Mirror GitHub Repository into GitLab Workspace  #
# Copyright (C) 2024 Progyan Bhattacharya <bprogyan@gmail.com>                #
#                                                                             #
# This program is free software; you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation; either version 2 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License along     #
# with this program; if not, write to the Free Software Foundation, Inc.,     #
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.                 #
###############################################################################
---
name: "GitLab Mirror Action"
description: "Mirror Commit History of GitHub Repository into GitLab Workspace."
author: "Progyan Bhattacharya <bprogyan@gmail.com>"

inputs:
  follow-tags:
    description: "Enable this boolean flag to push Tags alongside."
    required: false
    default: "false"

  force-push:
    description: "Enable this boolean flag to overwrite Git history."
    required: false
    default: "false"

  hostname:
    description: "Provide hostname for self-hosted GitLab instance."
    required: false
    default: "gitlab.com"

  password:
    description: "Password or Access Token for GitLab User."
    required: true

  project-id:
    description: "Project Id for the target Repository."
    required: true

  username:
    description: "Username for GitLab User."
    required: true

runs:
  using: "composite"
  steps:
    - name: Mirror Repository
      shell: bash
      env:
        FOLLOW_TAGS: "${{ inputs.follow-tags }}"
        FORCE_PUSH: "${{ inputs.force-push }}"
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITLAB_HOSTNAME: ${{ inputs.hostname }}
        GITLAB_PASSWORD: ${{ inputs.password }}
        GITLAB_PROJECT_ID: ${{ inputs.project-id }}
        GITLAB_USERNAME: ${{ inputs.username }}
      run: |-
        url="https://$GITLAB_HOSTNAME/$GITLAB_USERNAME/$GITLAB_PROJECT_ID.git"
        branch=$(git symbolic-ref --short HEAD)

        git config core.askPass "$GITHUB_ACTION_PATH/ask-pass.sh"
        git config credential.username "$GITLAB_USERNAME"
        git config credential.helper cache
        git config pull.ff only
        git remote add mirror $url
        git fetch mirror

        if [ "${FORCE_PUSH:-}" = "true" ]
        then
          git push --force mirror $branch
        else
          git push mirror $branch
        fi

        if [ "${FOLLOW_TAGS:-}" = "true" ]
        then
          git push --tags mirror
        fi

branding:
  icon: "git-pull-request"
  color: "blue"
